---

- name: install nginx
  yum:
    name: nginx
    state: present

- name: start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: stop firewalld service
  systemd:
    name: firewalld
    state: stopped
    enabled: no