---
- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Start nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: false

- name: Stop firewalld service
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false
