{
 "title": "System",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Использование ЦП (ср за 1м)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node.*\"}",
     "legendFormat": "CPU usage - {{instance}}"
    }
   ]
  },
  {
   "title": "Использование ЦП (ср за 5м)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load5{instance=~\"$node.*\"}",
     "legendFormat": "CPU usage - {{instance}}"
    }
   ]
  },
  {
   "title": "Использование ЦП (ср за 15м)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load15{instance=~\"$node.*\"}",
     "legendFormat": "CPU usage - {{instance}}"
    }
   ]
  },
  {
   "title": "Свободная память",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node.*\"} / 1024 / 1024 / 1024",
     "legendFormat": "Free ram on {{instance}}"
    }
   ]
  }
 ]
}