---
### CREATE DIR'S ###
- name: Create dir
  ansible.builtin.file:
    path: "{{ site_path }}/{{ site_name }}"
    state: directory
    mode: "0755"

- name: Copy site files to server
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: "{{ site_path }}/{{ site_name }}/{{ item }}"
    mode: "0744"
  loop:
    - index.html
    - style.css
    - d3js.js

### PROVIDE CONFIGS ###
- name: Provide nginx config
  ansible.builtin.template:
    src: templates/config.conf.j2
    dest: "{{ nginx_config_path }}/{{ site_name }}.conf"
    mode: "0644"

### START SERVICES ###
- name: Start service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true
